### ISSUE TITLE
Hover text on Receive coins list displays impossible suggestion

### ISSUE THREAD

**Issue by johanso-au** [nukeling/Wyvern#11]
Windows 10 - x64 - Wyvern 1.0 QT Wallet

Hovering the cursor over an address of label displays: "Double-click to edit address or label".

Double-clicking on the label section will allow edits, however double-clicking on the address does nothing. Besides, you can't _edit an address_ anyway.

Suggest to change text in "src/qt/forms/addressbookpage.ui", line 45, and all translations (just a few, lol) to "Double-click on label to edit".

**Comment by ColonelClink** [comment]
Fixed and ready to be merged: #12
