### ISSUE TITLE
wyvernd requires shared libraries.

### ISSUE THREAD

**Issue by johanso-au** [nukeling/Wyvern#5]
The wyvernd in 'wyvernd.7z' does not play nicely on a fresh Ubuntu / Debian install. Seems to require libboost 1.54 libraries to be available.

Steps to reproduce:
1. Spin up new VM (Debian 14 in this case) - fresh install
2. "apt-get install p7zip-full"
3. "wget --no-check-certificate https://github.com/nukeling/Wyvern/raw/master/wyvernd.7z" 
4. "z7 x wyvernd.7z"
5. "chmod +x wyvernd"
6. "./wyvernd"

Error displayed:
"./wyvernd: error while loading shared libraries: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory"

While I don't understand the root cause, a compile from source from the same environment produces a "wyvernd" that works as expected.
Also note that libboost-1.55 was the version used in the rebuild.

**Comment by johanso-au** [comment]
Okay, found the problem. The daemon needs to be built with the static flag set, i.e: "make -f makefile.unix STATIC=1".

Also, running "strip wyvernd" after compilation will shrink the file to 2.49MB.

**Comment by johanso-au** [comment]
Correction to above: Shrunk wyvernd is approx 6mb, 2.5mb as a tar.gz.

**Comment by ColonelClink** [comment]
Thanks. I will upload a statically linked version of the binary over the weekend when I have more time.

**Comment by johanso-au** [comment]
Thanks. Can we upload it as a tar.gz? The 7zip format requires a non-standard app to decompress on vanilla Ubuntu/Deb, where tar is a standard inclusion.

**Comment by ColonelClink** [comment]
Yes, I will upload both a tar.gz and zip file.

**Comment by ColonelClink** [comment]
Fixed. @nukeling please mark as resolved.

**Comment by nukeling** [comment]
gladly :)
