### ISSUE TITLE
Included 'leveldb' will not compile from source on Debian/Ubuntu

### ISSUE THREAD

**Issue by johanso-au** [nukeling/Wyvern#6]
It appears that the included 'leveldb' may be the version used in a Windows compile(??).

This causes an issue when compiling the wyvernd daemon from makefile.unix.

The solution for me was to bring in a different source (known working) to replace the ../src/leveldb/

Request a volunteer to test building from source on a Debian / Ubuntu fresh install to confirm issue.

**Comment by johanso-au** [comment]
On further inspection (Diff of the two leveldb versions) I can see that the version included here is 1.15, and the build succeeded on 1.12.

**Comment by ColonelClink** [comment]
I was able to get v1.15 to compile by entering ` ../src/leveldb` and running `make libleveldb.a libmemenv.a`. The makefile may need updating.

**Comment by ColonelClink** [comment]
Oddly enough, compiling on Ubuntu 14.04 works fine.

**Comment by johanso-au** [comment]
I was on 14.04 when I had the issue. Hmm... might close this one for now, then. Possibly my config.
