### ISSUE TITLE
No Genesis Block Hash exists for testnet

### ISSUE THREAD

**Issue by johanso-au** [nukeling/Wyvern#8]
Loading with the -testnet flag results in an error.

Generating the testnet genesis hash and adding that doesn't completely solve the issue, though. (I found 0x3249c8541cc9e9ee7de2192a6b3c2338c7a7d5aea546078cf9d6e3fe5ab1228c to be the testnet genesis hash on multiple machines)

The error:
ERROR: CheckProofOfWork() : hash doesn't match nBits

Followed by a POW failure (expected).

Seems to have something to do with the nBits (0x1f00ffff) or expected difficulty. Spent a bit of time trying to solve it, but this issue is a bit beyond me.

**Comment by ColonelClink** [comment]
The testnet is a feature to be enabled later if needed. Still, this is an interesting bug, as it shouldn't fail the POW check.

**Comment by johanso-au** [comment]
Here's the code change for line 55 of main.h, which should be confirmed. I'll raise the pull req:

main.h#L55: static const uint256 hashGenesisBlockTestNet("0x3249c8541cc9e9ee7de2192a6b3c2338c7a7d5aea546078cf9d6e3fe5ab1228c");

**Comment by johanso-au** [comment]
Okay - Found the solution. The issue is now that the default dnsseed is not running the testnet, therefor the clients have to use the *shudder* IRC solution to find peers.

@ColonelClink can you please make the edits, test and pull?

main.h#L55: static const uint256 hashGenesisBlockTestNet("0x00003207d4daa5f3ae62d42abbd0387a9f6ca4f881ac2f0f1ae2c335058af8ef");

main.cpp#L2510:  block.nNonce   = 49669;

I'm testing now on two machines, so you should see these on peerinfo.

**Comment by ColonelClink** [comment]
Fixed and in pull request #15

**Comment by johanso-au** [comment]
Closed
